// Code generated by MockGen. DO NOT EDIT.
// Source: grade_service_interface.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/grade_service_mock.go -package=mocks -source=grade_service_interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	gradeRepository "sms/repository/gradesRepository"

	gomock "go.uber.org/mock/gomock"
)

// MockGradeServiceI is a mock of GradeServiceI interface.
type MockGradeServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockGradeServiceIMockRecorder
	isgomock struct{}
}

// MockGradeServiceIMockRecorder is the mock recorder for MockGradeServiceI.
type MockGradeServiceIMockRecorder struct {
	mock *MockGradeServiceI
}

// NewMockGradeServiceI creates a new mock instance.
func NewMockGradeServiceI(ctrl *gomock.Controller) *MockGradeServiceI {
	mock := &MockGradeServiceI{ctrl: ctrl}
	mock.recorder = &MockGradeServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeServiceI) EXPECT() *MockGradeServiceIMockRecorder {
	return m.recorder
}

// AddGrades mocks base method.
func (m *MockGradeServiceI) AddGrades(studentID, subjectID string, Grade, semester int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGrades", studentID, subjectID, Grade, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGrades indicates an expected call of AddGrades.
func (mr *MockGradeServiceIMockRecorder) AddGrades(studentID, subjectID, Grade, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGrades", reflect.TypeOf((*MockGradeServiceI)(nil).AddGrades), studentID, subjectID, Grade, semester)
}

// GetAverageOfClass mocks base method.
func (m *MockGradeServiceI) GetAverageOfClass(classID string, semester int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageOfClass", classID, semester)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageOfClass indicates an expected call of GetAverageOfClass.
func (mr *MockGradeServiceIMockRecorder) GetAverageOfClass(classID, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageOfClass", reflect.TypeOf((*MockGradeServiceI)(nil).GetAverageOfClass), classID, semester)
}

// GetToppers mocks base method.
func (m *MockGradeServiceI) GetToppers(classID string, semester, top int) ([]gradeRepository.StudentAverage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToppers", classID, semester, top)
	ret0, _ := ret[0].([]gradeRepository.StudentAverage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToppers indicates an expected call of GetToppers.
func (mr *MockGradeServiceIMockRecorder) GetToppers(classID, semester, top any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToppers", reflect.TypeOf((*MockGradeServiceI)(nil).GetToppers), classID, semester, top)
}

// UpdateGrade mocks base method.
func (m *MockGradeServiceI) UpdateGrade(studentID, subjectID string, newGrade int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGrade", studentID, subjectID, newGrade)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGrade indicates an expected call of UpdateGrade.
func (mr *MockGradeServiceIMockRecorder) UpdateGrade(studentID, subjectID, newGrade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGrade", reflect.TypeOf((*MockGradeServiceI)(nil).UpdateGrade), studentID, subjectID, newGrade)
}
