// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGradeRepositoryI is a mock of GradeRepositoryI interface.
type MockGradeRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockGradeRepositoryIMockRecorder
}

// MockGradeRepositoryIMockRecorder is the mock recorder for MockGradeRepositoryI.
type MockGradeRepositoryIMockRecorder struct {
	mock *MockGradeRepositoryI
}

// NewMockGradeRepositoryI creates a new mock instance.
func NewMockGradeRepositoryI(ctrl *gomock.Controller) *MockGradeRepositoryI {
	mock := &MockGradeRepositoryI{ctrl: ctrl}
	mock.recorder = &MockGradeRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeRepositoryI) EXPECT() *MockGradeRepositoryIMockRecorder {
	return m.recorder
}

// AddGrades mocks base method.
func (m *MockGradeRepositoryI) AddGrades(studentID, subjectID string, Grade, semester int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGrades", studentID, subjectID, Grade, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGrades indicates an expected call of AddGrades.
func (mr *MockGradeRepositoryIMockRecorder) AddGrades(studentID, subjectID, Grade, semester interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGrades", reflect.TypeOf((*MockGradeRepositoryI)(nil).AddGrades), studentID, subjectID, Grade, semester)
}

// GetSemesterGrades mocks base method.
func (m *MockGradeRepositoryI) GetSemesterGrades(studentID string, semester int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSemesterGrades", studentID, semester)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSemesterGrades indicates an expected call of GetSemesterGrades.
func (mr *MockGradeRepositoryIMockRecorder) GetSemesterGrades(studentID, semester interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSemesterGrades", reflect.TypeOf((*MockGradeRepositoryI)(nil).GetSemesterGrades), studentID, semester)
}

// UpdateGrade mocks base method.
func (m *MockGradeRepositoryI) UpdateGrade(studentID, subjectID string, newGrade int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGrade", studentID, subjectID, newGrade)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGrade indicates an expected call of UpdateGrade.
func (mr *MockGradeRepositoryIMockRecorder) UpdateGrade(studentID, subjectID, newGrade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGrade", reflect.TypeOf((*MockGradeRepositoryI)(nil).UpdateGrade), studentID, subjectID, newGrade)
}
